api_platform:
    title: 'TFG Management API'
    version: '1.0.0'
    
    # Configuración global de paginación
    defaults:
        pagination_enabled: true
        pagination_page_parameter_name: 'page'
        pagination_items_per_page_parameter_name: 'per_page'
        pagination_items_per_page: 10
        pagination_maximum_items_per_page: 100
        pagination_partial: false
        pagination_client_enabled: true
        pagination_client_items_per_page: true
        pagination_fetch_join_collection: true
    
    # Deshabilitar JSON-LD completamente y usar solo JSON
    formats:
        json: ['application/json']
    
    patch_formats:
        json: ['application/json']
    
    # Deshabilitar JSON-LD en documentación y errores
    docs_formats:
        json: ['application/json']
        html: ['text/html']
    
    error_formats:
        json: ['application/json']
    
    # Configuración adicional para forzar JSON
    doctrine:
        enabled: true
        
    # Configuración de documentación
    swagger:
        versions: [3]
        
    # Configuración de CORS
    http_cache:
        invalidation:
            enabled: false