nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['*']
        allow_headers: ['*']
        allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
        expose_headers: ['Link', 'X-Total-Count', 'X-Page-Count']
        max_age: 3600
        allow_credentials: false
        
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_headers: ['*'] 
            allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
            max_age: 3600