nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: 
            - '%env(CORS_ALLOW_ORIGIN)%'
            - 'http://localhost:3000'
            - 'http://localhost:5173'
            - 'http://127.0.0.1:3000'
            - 'http://127.0.0.1:5173'
        allow_headers:
            - 'Accept'
            - 'Accept-Language'
            - 'Authorization'
            - 'Cache-Control'
            - 'Content-Language'
            - 'Content-Type'
            - 'DNT'
            - 'If-Modified-Since'
            - 'Keep-Alive'
            - 'Origin'
            - 'User-Agent'
            - 'X-Requested-With'
        allow_methods:
            - 'GET'
            - 'POST'
            - 'PUT'
            - 'PATCH'
            - 'DELETE'
            - 'OPTIONS'
        expose_headers:
            - 'Link'
            - 'X-Total-Count'
            - 'X-Page-Count'
        max_age: 3600
        
    paths:
        '^/api/':
            allow_origin: 
                - 'http://localhost:3000'
                - 'http://localhost:5173'
                - 'http://127.0.0.1:3000'
                - 'http://127.0.0.1:5173'
            allow_headers: ['*']
            allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
            max_age: 3600
            
        '^/':
            # Permitir CORS para todas las rutas
            origin_regex: true
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']