vich_uploader:
    db_driver: orm
    
    mappings:
        tfg_documents:
            uri_prefix: /uploads/tfgs
            upload_destination: '%kernel.project_dir%/public/uploads/tfgs'
            namer: App\Service\TFGFileNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            
    metadata:
        type: attribute